services:
  backend:
    build:
      context: ./backend
    container_name: todo-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

  frontend:
    build:
      context: ./frontend
    container_name: todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend