services:
  postgres:
    image: postgres:13
    container_name: todo-postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: todo-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - STORAGE_TYPE=postgres
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres/tododb
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
