name: Build, Test and Package

on:
  pull_request:
    branches:
      - main

jobs:
  build-test-package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Generate version string
        id: version
        run: echo "VERSION=1.0.${{ github.run_number }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Run Backend Tests
        run: docker compose run --rm backend python -m pytest tests -v 

      - name: Run Frontend Tests
        run: docker compose run --rm frontend npm test -- --watchAll=false

      - name: Build Docker images
        run: docker compose build
        
      - name: Package Docker images
        run: |
          mkdir -p release
          docker save todo-app_backend:latest > release/backend.tar
          docker save todo-app_frontend:latest > release/frontend.tar
          tar -czf todo-app-${{ steps.version.outputs.VERSION }}.tar.gz release

      - name: Upload application artifact
        uses: actions/upload-artifact@v4
        with:
          name: todo-app-package-${{ steps.version.outputs.VERSION }}
          path: todo-app-*.tar.gz
